### PR TITLE
Update .gitignore with project-relevant ignores

### PR DESCRIPTION
**Pull request by philipmw**

### CODE REVIEW

**Comment by barbeau** [comment]
ICLA manually verified :+1:

**Comment by barbeau** [comment]
Thanks @philipmw!  I'm fine with adding the IntelliJ files to .gitignore, but does this remove Eclipse-generated files?  I'm not in front of my machine so I can't verify.

**Comment by philipmw** [comment]
Yeah I removed them because I assumed they were autogenerated. I re-added them. So now this just adds IntelliJ and Maven temp files.

**Comment by barbeau** [comment]
Awesome, thanks @philipmw!

**Pull request merged**
