### PR TITLE
Fix #48 - Add more utterances

### LINKED ISSUE #48: More utterances
**Summary:**

Amazon wants more permutations of utterances, especially for getting arrival times.  Apparently "When is the next Bus?" currently fails.

**Steps to reproduce:** 

Open skill.

**Expected behavior:** 

More cowbell.

**Observed behavior:** 

Not enough cowbell.

### PR DESCRIPTION
**Pull request by barbeau**
* Add "leave" and "departs" in addition to "arrives"
* Add most transit types that are listed in GTFS at https://developers.google.com/transit/gtfs/reference#routestxt.
* Add a few other phrases

### CODE REVIEW

**Comment by barbeau** [comment]
@philipmw Could you take a look at this tonight and merge if all looks ok?  Trying to get this and https://github.com/OneBusAway/onebusaway-alexa/issues/49 fixed in the next few days so Amazon can publish skill to beta.

**Comment by philipmw** [comment]
Howdy, @barbeau. I propose that we use Alexa's word banks feature. We can create a word bank named, say, "TransitModes", and fill it with [bus, train, metro, subway, ...]. Then we can use the TransitModes variable inside our utterances. This keeps our list of utterances tractable.

**Comment by barbeau** [comment]
Ah, nice, didn't know about word banks.  That's definitely a better solution.

**Comment by barbeau** [comment]
@philipmw Where the heck is the documentation for Alexa word banks?  One of my pet peeves with Alexa is Amazon's documentation - it always seems impossible to find what I'm looking for.

**Comment by barbeau** [comment]
So I asked Alexa dev team about the concept of word banks and if the were supported, and this was their response:

>Not really. There are a lot of 3rd party libs, node modules (like alexa-app) etc. that might do that  - I would not recommend that route.

>Your best result will be to spend the time to spell everything out for each transit mode – we know that will work, and it will not take near as long as you think it will!

@philipmw Let's just stick with the current utterances then.  If you can review/merge this and the other PR we can get the skill into beta this week.

**Comment by barbeau** [comment]
Please hold on merging this - heard back from Amazon again, there is a way to emulate word banks vis custom slots.  I'll update this with the new solution.

**Comment by philipmw** [comment]
I am glad you heard back on custom slots. Thats what I originally meant, and it works very well in another skill I developed. I just didnt get around to writing that up.

**Comment by barbeau** [comment]
@philipmw Ok, this should be ready for review/merge again.  Added a custom slot for `TRANSIT_MODES`.

**Pull request merged**
