### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by philipmw**
For some MYSTERIOUS REASON, unit tests on master are failing on my workstation, but they pass in Travis CI. I fixed some mocking that I think make the tests more correct...

### CODE REVIEW

**Comment by barbeau** [comment]
Probably due to some state being retained on your machine, as Travis is always clean.  I'll take a look at this tomorrow so I can verify it passes on my machine too.

**Comment by barbeau** [comment]
Passes on my local machine too.

So why did code coverage go down with these changes?

**Comment by philipmw** [comment]
So did both ways pass on your machine? Looking at the code, can you see why this is more correct?

**Comment by barbeau** [comment]
Yes, both ways pass on my machine.  I think so - so this isolates the obaDao to a single unit test, vs. The state being exposed to all tests?  I still need to read the JMockit docs in detail.

**Pull request merged**
