### PR TITLE
Fix #63 - Address certification feedback

### LINKED ISSUE #63: Address certification feedback
Below is feedback from the Alexa certification team that we need to address before public launch (which requires another submission to certification with the below items resolved).  I opened a WIP PR at https://github.com/OneBusAway/onebusaway-alexa/pull/64 with individual commits to address the below items, and will check them off as they are addressed.

------------

**Requirements:**
 
- [x] The invocation name you have chosen for your skill does not follow all conventions for choosing a name and is unlikely to have high accuracy for launching your skill.  Please change your invocation name to "one bus away".  For more information on invocation name guidelines, please visit: https://developer.amazon.com/appsandservices/solutions/alexa/alexa-skills-kit/docs/choosing-the-invocation-name-for-an-alexa-skill
 
- [x] The AMAZON.US_CITY slot type only includes cities with a population of over 100,000. You should expand the AMAZON.US_CITY slot type and include the following as slot values:
 
>rogue valley
york
york region
tampa bay
puget sound
san diego m. t. s.
 
Additionally, consider adding any other city/area name variation that you think users might say. For more information on expanding built-in slot types, please visit: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#Extending%20a%20Built-in%20Slot%20Type%20with%20Custom%20Values
 
- [x] An error occurs when saying the second example phrase. The example phrases must function without error since these are interactions that users are most likely to try. Please see test case 3.1 from our Submission Checklist for guidance on example phrases.  Request ID: amzn1.echo-api.request.360a5f86-9117-4dcc-80eb-c6c2a98fb6c1
 
- [x] The skill does not exit/respond appropriately when users say “stop” or “cancel”. Please see test case [4.13 from our Submission Checklist](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-interface-and-user-experience-testing#4.13. Intent (Exit)) for guidance on skill exiting.
 
**Recommendations:**
 
- [x] We recommend adding the following sample utterance as it is likely that users will respond to the stop ID prompt with only the stop number:
 
>SetStopNumberIntent     {stopNumber}
 
- [x] Errors in the tokenization of acronyms and initialisms can greatly impact the speech recognition for your skill. All instances of "id" should be changed to "i. d.".
 
- [x] The skill will work best for users when you include utterances that can easily work on their own, as well as utterances that work well to follow the one-shot launch phrasing. Consider adding the following types of sample utterances:
 
>Commands (Work well after "ask onebusaway to..." or "tell onebusaway to...")
 
>GetCityIntent      get my current city
GetCityIntent      tell me my current city
GetStopNumberIntent     tell me what my stop is
GetArrivalsIntent              get me arrival times
etc.
 
>Noun Phrases (Work well after "ask onebusaway for...")
 
>GetCityIntent      my current region
GetCityIntent      my city
GetStopNumberIntent     my current stop
GetStopNumberIntent     my stop
GetArrivalsIntent              the arrival times of my {TransitMode}
GetArrivalsIntent              {TransitMode} times
etc.
 
>Interrogative and Inverted Questions (Work well after "ask onebusaway...")
 
>GetArrivalsIntent              where's my {TransitMode}
GetArrivalsIntent              where {TransitMode} is
GetStopNumberIntent     what's my current stop
GetStopNumberIntent     what my stop is
GetCityIntent      what's my city
GetCityIntent      what my city is
etc.

### PR DESCRIPTION
**Pull request by barbeau**
I'll keep pushing commits here to address various items in #63, and check them off the list there as they are completed.

### CODE REVIEW

**Comment by barbeau** [comment]
@philipmw Could you please go ahead and start reviewing the commits in this WIP PR?

I'm going to try and tackle the last one related to utterances (mentioned in https://github.com/OneBusAway/onebusaway-alexa/issues/63#issuecomment-213652739) likely tomorrow.

**Comment by barbeau** [comment]
@philipmw Also, I should mentioned I haven't tested any of these commits with my Echo yet, so additional testing there would also be appreciated.

**Comment by barbeau** [comment]
@philipmw I think we're looking pretty good here.  Almost everything seems to be working well.

I'm still having issues with setting "Atlanta" as a city, though.  Could you do me a favor and try setting your city to Atlanta?

I've tested this by:

"Ask OneBusAway to set my city"

and then:

"Atlanta"

I'm not sure if it's just how I pronounce it, but based on the history in the Alexa app Alexa is hearing all kinds of variations that don't result in it getting the city name around 70% of the time, including:

* how lanta
* at lanta
* add lanta
* set lanta
* pet lanta
* have lanta
* lanta

It would be good to know if it's just me or a larger issue.

**Comment by barbeau** [comment]
Good news - Amazon said Atlanta recognition issue was on their end, should be fixed in release this weekend.

@philipmw Heads up - I'm going to do a last review and merge of this tonight (my time - so in roughly 3-4 hours) so I can re-submit for certification tonight.  If you can't get comments in before then we can fix in future PRs.

**Comment by philipmw** [comment]
It looks good to me.

**Pull request merged**
