### PR TITLE
Use JMockit; add unit tests

### PR DESCRIPTION
**Pull request by philipmw**
Addresses issue #18. I switched from Mockito to JMockit. This allows us to mock OBA libraries, so I wrote some new unit tests also.

### CODE REVIEW

**Comment by barbeau** [comment]
Cool!  Looks like this failed on Travis though:

~~~
<<< FAILURE! - in org.onebusaway.alexa.MainSpeechletEmptyTest
setRecognizableCity(org.onebusaway.alexa.MainSpeechletEmptyTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string starting with "Ok, you live in Seattle.  What's your stop number?"
     but: was "OneBusAway could not locate a OneBusAway installation in Seattle, the city you gave. Tell me again, in what city do you live?"
	at org.onebusaway.alexa.MainSpeechletEmptyTest.setRecognizableCity(MainSpeechletEmptyTest.java:115)
~~~

**Comment by philipmw** [comment]
Huh. It Works On My Desktop®. I'll look into it.

**Comment by barbeau** [comment]
Yeah, this fails on my local machine as well, same error.

**Comment by philipmw** [comment]
Ok. I will look into it in the next couple of days. I am beaching in sunny LA right now, down from gloomy drizzly Seattle.

**Comment by barbeau** [comment]
Sure, no rush.  Enjoy the sun :).

**Comment by philipmw** [comment]
I reproduced this problem. I guess it fails on my computer also. I am investigating.

**Comment by philipmw** [comment]
BAM. Passes. With this PR, I am satisfied with the initial state of our tests. These tests set a good example for how to test any part of the current system, including mocking OBA classes.

**Comment by barbeau** [comment]
Awesome, thanks @philipmw!  LGTM.  Great to have a set of solid unit tests.

**Pull request merged**
